import { Message } from '../types';

export const chatHistory: Message[] = [
  {
    id: 1,
    type: 0,
    from: 0,
    text: 'Ej, jesi li stigao pogledati onaj nacrt što sam ti poslao jučer?',
    url: null,
    replyTo: null,
    reactions: { value: 0, count: 0 },
  },
  {
    id: 2,
    type: 1,
    from: 1,
    text: null,
    url: 'https://picsum.photos/seed/design1/400/300',
    replyTo: null,
    reactions: { value: 1, count: 1 },
  },
  {
    id: 3,
    type: 0,
    from: 1,
    text: 'Mislim da bismo trebali promijeniti boju headera na ovome.',
    url: null,
    replyTo: null,
    reactions: { value: 0, count: 0 },
  },
  {
    id: 4,
    type: 0,
    from: 0,
    text: 'Slažem se. Evo kako sam ja to zamislio u novoj verziji:',
    url: null,
    replyTo: null,
    reactions: { value: 0, count: 0 },
  },
  {
    id: 5,
    type: 1,
    from: 0,
    text: null,
    url: 'https://picsum.photos/seed/design2/400/300',
    replyTo: null,
    reactions: { value: 0, count: 0 },
  },
  {
    id: 6,
    type: 0,
    from: 0,
    text: 'Samo da ti još javim par detalja prije kave. Razmišljao sam o onom dijelu s bazom podataka i mislim da bi bilo pametnije koristiti Redis za cacheiranje onih najčešćih upita kako bismo smanjili opterećenje. Također, trebao bih ti pokazati nove figma screenove koje sam napravio sinoć jer sam dodao dark mode opciju koja izgleda stvarno moćno. Ponesi laptop ako možeš da odmah prođemo kroz API dokumentaciju jer sam primijetio par endpointa koji bi mogli raditi probleme pri integraciji s frontendom. Vidimo se uskoro!',
    url: null,
    replyTo: null,
    reactions: { value: 0, count: 0 },
  },
  {
    id: 7,
    type: 0,
    from: 1,
    text: 'Uff, to zvuči kao dosta posla, ali imaš pravo za Redis. Nosim laptop, vidimo se za pol sata!',
    url: null,
    replyTo: null,
    reactions: { value: 1, count: 1 },
  },
  {
    id: 8,
    type: 0,
    from: 1,
    text: 'Možeš li mi samo poslati link na te nove Figma screenove prije nego krenem?',
    url: null,
    replyTo: 6,
    reactions: { value: 0, count: 0 },
  },
  {
    id: 9,
    type: 0,
    from: 0,
    text: 'Naravno, šaljem odmah!',
    url: null,
    replyTo: 8,
    reactions: { value: 0, count: 0 },
  },
];
